packages:
  - playground
  - examples/*

ignoreWorkspaceRootCheck: true
shamefullyHoist: true
strictPeerDependencies: false

onlyBuiltDependencies:
  - esbuild
  - sharp
  - svelte-preprocess
  - unrs-resolver
  - vue-demi
